### ISSUE TITLE
Have you used it with Material UI 1.0.0?

### ISSUE THREAD

**Issue by sunny-sideup** [dockwa/simple-react-validator#10]
It's not a issue but more of a question. Can you help me use this with material UI? I have used it with MI  errors but it creates a <div> inside a <p> which gives an error. Can you help me with this.
```
<p class="MuiFormHelperText-root-69" id="name-helper-text">
    <div class="validation-message">The company name field is required.</div>
</p>

```

**Comment by stuyam** [comment]
You are saying want it not wrapped inside of another `<div>` am I understanding that correctly?

**Comment by stuyam** [comment]
Support for this is coming in the next major release, you can track here: https://github.com/dockwa/simple-react-validator/pull/20
