### ISSUE TITLE
Email verification makes the field required 

### ISSUE THREAD

**Issue by sunny-sideup** [dockwa/simple-react-validator#11]
Hi,

I have two fields in my form 
1. Email (required)
2. Alternative Email (optional)

but when I use the 'email' validator in the alternate email field, without the required validator, it automatically makes the Alternative Email required. 

In other words I want the Alternative Email to be blank.

**Comment by stuyam** [comment]
This fix is coming in the next major release, follow along here: https://github.com/dockwa/simple-react-validator/pull/20
