### ISSUE TITLE
it does not work with typescrypt

### ISSUE THREAD

**Issue by apocales** [dockwa/simple-react-validator#117]
I'm doing a web application with "create-react-app --typescript" but it throws the following error when including "simple-react-validator"
![imagen](https://user-images.githubusercontent.com/15135408/61161641-bfd4ea00-a4d2-11e9-9967-a6e967371a42.png)
I think it's because the definitions file of typescript is missing, but it does not exist yet (npm install @ types / simple-react-validator does not find anything)

**Comment by NielsB95** [comment]
When can we expect #116 to be released? :)

**Comment by stuyam** [comment]
@NielsB95 thanks for the reminder. Pushing it out as we speak.

**Comment by stuyam** [comment]
@NielsB95 out now: https://github.com/dockwa/simple-react-validator/releases/tag/1.2.1
