### ISSUE TITLE
It's not working with redux actions?

### ISSUE THREAD

**Issue by cihanzenginff** [dockwa/simple-react-validator#118]
Hello, plugin is not working with redux actions which trigging onChange? 

i have an input: 

`<input
                            name="name"
                            value={this.props.form.name}
                            required="required"
                            onChange={event =>
                              this.props.getName(event.target.value)
                            }
                          />`

and validator: 
` {this.validator.message('n', this.props.form.name, 'required|alpha')}
`

i wan't to show message at onChange but message not showing. 
with interesting way validation working when at onClick submit button if i will call validAll method.

**Comment by stuyam** [comment]
Yes you can either use the `onBlur` stuff or you can manually turn on all messages with `showMessages` method.
