### ISSUE TITLE
Passing rules results

### ISSUE THREAD

**Issue by k-jano** [dockwa/simple-react-validator#123]
In _simple-react-validator_ we can use _allValid()_ method to validate all fields and _fieldValid(field)_ to validate single field. We can only get boolean if value pass all rules or not.

So here is my question, is it possible to add method provide us which rules value doesn't pass? For every rule we could get boolean if input value pass it or not. For example if I have this field:

``this.validator.message('email', this.state.email, ['required', 'email'])``

and I want to know which rules my input pass I can call:

``this.validator.passedRules('email') // [true, false]``

It could be very useful to me and perhaps to other users. I would be grateful if You can take up my problem. Thank You for developing this helpful library.

**Comment by stuyam** [comment]
Would need a bit of work to make this happen, and would add some some surface area. Curious what you have the need for and if there is another way we we could help you accomplished what you are trying to do.

**Comment by kjano10** [comment]
Let me describe my case. In every form, in case of validation failure I want to display tooltip with requirements which entered value doesn't pass.

I see that you provide ``getErrorMessages()``. It's very useful, but doesn't meet my expectations. It gives me single custom message. It is possible to extend this method? If I could overwrite custom messages and get it all, I would display it to user in easy way. 

Please note, that error message could concatenate many smaller messages. For example: value doesn't match required complex pattern, so error message should be a list with individual messages.

**Comment by golamrabbi3** [comment]
Hey, @stuyam you built a great plugin, I appreciate that. :)
I am calling allValid() function onChange event of any field. 
It seems the allValid() function does not return true even the form passes all the validation on changes. 

My expectation is while all fields are validated the submit button will be enabled automatically. It doesn't work. I also set {autoForceUpdate: this} but doesn't help. 

Please suggest me possible solution if possible :)

**Comment by stuyam** [comment]
Closing stale.
