### ISSUE TITLE
Code base is missing export statement after installation

### ISSUE THREAD

**Issue by Lucisd** [dockwa/simple-react-validator#125]
My simple-react-validator/src/index.d.ts file is missing the export statement.

**Comment by stuyam** [comment]
Is this not right? https://github.com/dockwa/simple-react-validator/blob/master/src/index.d.ts#L70

**Comment by Lucisd** [comment]
Yes, that is perfect. The issue is that that last export statement is missing in my project, after installation. Do you have any advice?

**Comment by cristian1703** [comment]
I have the same problem. After installing the library the last line from the index file is missing in my node_modules (the one with export default)

**Comment by stuyam** [comment]
Im open to suggestions, I don't know enough about typescript to know what it should be doing.
