### ISSUE TITLE
autoForceUpdate type issue

### ISSUE THREAD

**Issue by sukhminderx** [dockwa/simple-react-validator#126]
Hi,

The type of autoForceUpdate is defined as a boolean as:
`
interface IOptions {
  messages?: any;
  className?: any;
  autoForceUpdate?: boolean;
  element?: any;
  locale?: string;
}
`
but the documentation states it should get the component instance 'this'.
Hence, it gives an error here:
`
        forceUpdateIfNeeded: function () {
          this.parent.autoForceUpdate && this.parent.autoForceUpdate.forceUpdate();
        },`

The error is:
`this.parent.autoForceUpdate.forceUpdate is not a function`

Please have a look. I think the type of the prop should be modified.

**Comment by stuyam** [comment]
I'm not super familiar with Typescript but that sounds like it is wrong. Feel free to open a pull request if you have an idea of how to fix it.

**Comment by e-gauthier** [comment]
You can find a Pull Request #134 that resolve this issue.

**Comment by stuyam** [comment]
Merged #134
