### ISSUE TITLE
showMessageFor function is not defined 

### ISSUE THREAD

**Issue by shakti97** [dockwa/simple-react-validator#127]
showMessageFor function is not defined 
![this validator showMessageFor](https://user-images.githubusercontent.com/30585570/62428087-18d31f00-b71b-11e9-9745-32a1e9eadb7c.PNG)

**Comment by stuyam** [comment]
Could you post a code example maybe? You probably need to bind the callback to your current class so it has access to `this.validator` if you are using it with `onBlur` for example.

**Comment by shakti97** [comment]
<input type="text" className="form-control" onBlur={()=>this.validator.showMessageFor('name')}/>
gives above error whereas 
<input type="text" className="form-control" onBlur={()=>this.validator.showMessages()}/>
works fine

**Comment by shakti97** [comment]
By bad,Closing this issue actually i was working with older version @stuyam
