### ISSUE TITLE
ShowMessages() is not working for first time

### ISSUE THREAD

**Issue by Hacivat** [dockwa/simple-react-validator#129]
```
  doSomething(event) {
    event.preventDefault()
    if (this.validator.allValid()) {
     // ...
    } else {
      console.log(this.state)
      this.validator.showMessages()
    }
  }

```
Doesn't work for first time. But when i triggered some onBlur function then showMessages() worked.

**Comment by stuyam** [comment]
You need to force update. Either do:
```jsx
this.validator.showMessages()
this.forceUpdate()
```

Or use the autoForceUpdate when you initialize the validator: https://github.com/dockwa/simple-react-validator#note-autoforceupdate
```jsx
constructor() {
  this.validator = new SimpleReactValidator({autoForceUpdate: this});
}
```

**Comment by Hacivat** [comment]
It worked. Thanks!

**Comment by jainam-shah-cygnet** [comment]
I am getting same issue. I am using react hooks to implement my app. so how can we get it work with hooks?
