### ISSUE TITLE
Password and confirm password validation

### ISSUE THREAD

**Issue by srinivas025** [dockwa/simple-react-validator#13]
How to do password and confirm password validation?

**Comment by stuyam** [comment]
@srinivas025 like doing validation that the two are equal?

**Comment by srinivas025** [comment]
@stuyam yea like creating a rule to validate password or is there a way to do using simple react validator?

**Comment by stuyam** [comment]
well for the first part validating password, it's up to you how you want to do that. You can set a min character limit, that is usually all I would do and make it required so like `required|min:8` will make it required and a minimum of 8 characters.

As for confirming that passwords are equal you could do that manually using the `customMessage` method that will show a message that you can generate if they are not equal. It's possible this could be built as a validator but would need to rework things a little in how the validator works I think.

**Comment by fuchsberger** [comment]
Since I had the same problem, here is how I solved it:

First, create a validator for the confirm_password field. Then simply print a custom message instead of the default one:
```javascript
render() {
  const { new_password, confirm_password } = this.state
  this.validator.purgeFields();
  const confirmPasswordError = this.validator.message('confirm_password', confirm_password, `required|in:${new_password}

  return(
  <Input
    error={confirmPasswordError}
    label={!this.validator.fieldValid('confirm_password') && 'Passwords need to match!'}
    name='confirm_password'
    onChange={this.onInputChange}
    placeholder='Confirm password'
    type='password'
    value={confirm_password}
  />)
}
```

**Comment by stuyam** [comment]
This is a great solution! Is there a reason you don't use the `message` method in the return with a custom message? You should be able to do something like:
```jsx
this.validator = new SimpleReactValidator({
  messages: {
    in: 'Passwords need to match!'
  }
})
...
this.validator.message('confirm_password', this.state.confirm_password, `required|in:${this.state.new_password}`)
```

Or even in one line:
```jsx
this.validator.message('confirm_password', this.state.confirm_password, `required|in:${this.state.new_password}`, {messages: {in: 'Passwords need to match!'}})
```

Thanks for sharing your example this is very smart. I wonder if maybe we could add a `match` validator which would basically just add a different message. I mean doing a custom message is easy enough so I guess it is not that big of a deal but something to think on. I definitely want to document this example though at the very least! Thanks @fuchsberger

**Comment by fuchsberger** [comment]
no problem. thanks for your response!
there is no reason I handled the message that way. Guess, I didn't realize I can customize the messages individually that easily.
