### ISSUE TITLE
Cyrillic symbols

### ISSUE THREAD

**Issue by DvoeglazovIlya** [dockwa/simple-react-validator#131]
I use this rule "alpha_space" and when I type "Илья", I receive "The name may only contain letters and spaces."
Cyrillic symbols didn't work

**Comment by stuyam** [comment]
We don't support Cyrillic symbols in the `alpha` validators we just check `a-z`. You will need to write a custom validator for that. Here is how you can do that, it should be pretty easy, let me know if you have any trouble: https://github.com/dockwa/simple-react-validator#custom-validators
