### ISSUE TITLE
hide all Messages

### ISSUE THREAD

**Issue by shakti97** [dockwa/simple-react-validator#132]
is there any method to hide all Messages irrespective they are invoke by showMessageFor or showMessages as hideMessages not working for both
I have a situation like, Consider a form , validating on Blur with showMessageFor when the user clicks on submit i m checking if all the fields are valid or not , if not showing messages using showMessages , if all valid then making api request and if the api request excutes successfully then need to remove all the field values from the state then the #IssueOccured all the messsage starts showing which are required.

**Comment by shakti97** [comment]
@stuyam any answer?

**Comment by stuyam** [comment]
There isn't a method or anything to do this but it should be pretty easy to do. You can see in the implementation that it just pushes onto an array for which field names have been shown: https://github.com/dockwa/simple-react-validator/blob/master/src/simple-react-validator.js#L93

So in theory you should just be able to do something like to clear the fields:
```jsx
this.validator.visibleFields = []
```

**Comment by shakti97** [comment]
Its not working correctly. It needs 
this.validator=[];
this.validator.hideMessages();
both of these function to hide all the messages

**Comment by stuyam** [comment]
Yeah depends on what you have turned on, you would need to force update which the `hideMessages` may be doing for you automatically.
