### ISSUE TITLE
In Typescript, options parameter  is mandatory.

### ISSUE THREAD

**Issue by e-gauthier** [dockwa/simple-react-validator#135]
The constructor of SimpleReactValidator set options as an empty object by default.  
It's the same for theses methods : 

- messageWhenPresent 
- messageAlways
- message

But, in Typescript, the value for options is mandatory.

`this.validator = new SimpleReactValidator({});`
or
`this.validator.message("title", this.state.title, 'required', {});`

index.d.ts should handle nullable for options so we can use it like this :

`this.validator = new SimpleReactValidator();`
or
`this.validator.message("title", this.state.title, 'required');`

**Comment by stuyam** [comment]
Sounds good to me, open a pull request!

**Comment by stuyam** [comment]
If you have a pull request for how to fix this I can merge it in and get all of your updates out in one release!

**Comment by e-gauthier** [comment]
Excellent!  I'm on it.

**Comment by e-gauthier** [comment]
A pull request has been created for this issue.  
#137

**Comment by e-gauthier** [comment]
@stuyam Can you wait before doing a release?  More issues are coming. (At least one)

**Comment by stuyam** [comment]
Yeah 👍

**Comment by stuyam** [comment]
Deploying in latest version.
