### ISSUE TITLE
Alpha num spaces validator

### ISSUE THREAD

**Issue by degaray** [dockwa/simple-react-validator#14]
It would be great to have an alpha_num validator which also accepts spaces. This is great for names.

**Comment by robertoaikode** [comment]
Any solution?

**Comment by stuyam** [comment]
I am always open to pull requests if someone is looking to make a change. What do people want? Should all the `alpha_*` validators allow spaces by default or should they be separate validators?

**Comment by stuyam** [comment]
Im leaning towards the `alpha_*` validators to accept spaces. Also going to add a regex validator that makes it easier to just pass in a regex one off. You can follow them in the next major release: https://github.com/dockwa/simple-react-validator/pull/20
