### ISSUE TITLE
showMessageFor keep adding the field in the internal visiblefields array even if it already existing.

### ISSUE THREAD

**Issue by e-gauthier** [dockwa/simple-react-validator#140]
Steps to reproduce : 

1. In a React component, create a Form.Input like this : 
`<Form.Input label="Name" placeholder="Name" value={this.state.name} onBlur={() => this.validator.showMessageFor("Name")} />`

2. Create a submit function and but a break point inside.

3. Run the component, enter and exit the textbox multiple time to trigger the onBlur.

4. Click submit button to trigger the breakpoint.

5. In the debugger, execute this line of code : 
`this.validator.visibleFields`

**Actual behavior :**
The visibleFields array contains multiple field name with the same name.

**Expected behavior :** 
showMessageFor should check if the field already exist and add it if not.

**Comment by stuyam** [comment]
Is this causing an error to occur? Definitely want to fix it either way but just curious if this causes an error?
