### ISSUE TITLE
Skip certain Field from allValid() function

### ISSUE THREAD

**Issue by ranggamp** [dockwa/simple-react-validator#145]
Just curious, can we skip certain (one or more) field validation from allValid() function..
thanks in advance

**Comment by stuyam** [comment]
In the current implementation no. Im wondering what you use case is though and if there is something I could help figure out, it is definitely possible to implement just curious how you would use it?

**Comment by ranggamp** [comment]
thanks @stuyam, 
Just consider this, we made hide element (text input with validation), here we can skip this input with allValid(), but when we show and hide this field again, it can skip allValid(). Even we put value on this input field, so allValid can checked and passed

**Comment by stuyam** [comment]
I think this is related, #146 I think what you both want to do is use the `purgeFields` method before rerendering so it will clear old validations and will only re add the ones in the view. https://github.com/dockwa/simple-react-validator#conditional-fields

It should be safe to use the `purgeFields` method it just isn't necessary if your form isn't dynamically changing.
