### ISSUE TITLE
How to Add Validation on Radio Buttons

### ISSUE THREAD

**Issue by KamranMaqbool** [dockwa/simple-react-validator#150]

**Comment by stuyam** [comment]
What are you trying to validate, like what are you wanting to happen?

**Comment by KamranMaqbool** [comment]
i have this radio fields
<label>Select Company Type: </label> <br/>
                            <div className="form-check form-check-inline mt-2">
                                <input className="form-check-input" onChange={this.handleDirect.bind(this)} type="radio" name="company_type" id="inlineRadio1" value="true" />
                                <label className="form-check-label">Direct</label>
                            </div>
                            <div className="form-check form-check-inline">
                                <input className="form-check-input" onChange={this.handleInDirect.bind(this)} type="radio" name="company_type" id="inlineRadio2" value="true" />
                                <label className="form-check-label">Indirect</label>
                            </div>
two different state property for this radio button how to validate ?

**Comment by stuyam** [comment]
Are you just trying to see if one is selected?

**Comment by KamranMaqbool** [comment]
I have two state variables 
1- region_one and 2- regio_two
first time no one radio button is selected. when I submit without select the radio button then give me error please select one region.
I am confusing how implement this validation
what i am providing in below  in the place of sample ?
{this.validator.message('sample', this.state.sample, 'required')}

**Comment by stuyam** [comment]
You should be able to do something like this:
```
{this.validator.message('region', this.state.region_one || this.state.region_two, 'required')}
```
