### ISSUE TITLE
Add Border Status

### ISSUE THREAD

**Issue by mtr1990** [dockwa/simple-react-validator#151]
Can we add this attribute?

**Comment by stuyam** [comment]
Can you give more details of what you are asking for?

**Comment by trinh294** [comment]
<img width="252" alt="Screenshot at Oct 03 10-28-02" src="https://user-images.githubusercontent.com/13531993/66097440-95be3000-e5c8-11e9-9f52-1e54dcf7566b.png">

As current your package, I only see a message when an error (I'm set text message =  color-red)
I have not found the border for it (I would like set border-input  =  color-red)
Did we have this attribute (status border-input when an error , success)?

**Comment by harrison-patel** [comment]
Any updates on this ?

**Comment by kerembeyazit** [comment]
Hello.

Am looking for this. This feature is very good!

**Comment by stuyam** [comment]
Duplicate of #128 solution was added there 👍
