### ISSUE TITLE
messageReplace not working

### ISSUE THREAD

**Issue by ldelosreyes** [dockwa/simple-react-validator#152]
I can't make it work. Here's my validation code

```
this.validator = new SimpleReactValidator({
      autoForceUpdate: this,
      validators: {
        oppMin: {
          message: textContent.quotePage.scriptings.purchasePriceMinimum,
          rule: value => {
            const category = this.state.categories.find(
              category =>
                category.assetHierarchyDescription === this.state.data.assetType
            );
            if (isEmpty(category)) {
              return;
            }
            const purchasePriceInDollars = parseFloat(value);
            const categoryMinPriceInDollars =
              parseFloat(category.purchasePriceFrom) / 100;
            return purchasePriceInDollars > categoryMinPriceInDollars;
          },
          messageReplace: message =>
            message.replace(
              ":icaContactNumber",
              textContent.constants.icaContactNumber
            )
        }
      }
    });
```

Here's what I'm getting

![image](https://user-images.githubusercontent.com/16955900/66186343-903e1400-e6b4-11e9-9251-caa415c32778.png)

**Comment by ldelosreyes** [comment]
I also noticed to the working example page that there are no `messageReplace` implementation. Is it because it is not really working? I'm hoping for your response since I really need to make it work. Thank you.

![image](https://user-images.githubusercontent.com/16955900/66359778-012e4600-e9ab-11e9-849d-954ec47c0c8e.png)

**Comment by stuyam** [comment]
Sorry I haven't had time to look at this yet but I haven't forgot about you @ldelosreyes I'm gonna take a look soon!

**Comment by JonVisc** [comment]
Any updates on this?  1.4.6 still doesn't have it working.  Thanks!

**Comment by MaximKoshevoy** [comment]
as a workaround you can just add property when using the validator.
`this.validator.message('price', this.state.price, 'oppMin:dummyValue'`

**Comment by weijie0192** [comment]
Is this fixed?

**Comment by stuyam** [comment]
I just used messageReplace yesterday on a project and it is working. MessageReplace is meant to allow you to replace some param from a validator into the message. For example the validator `max:32` would use messageReplace to add 32 to the validation message so it can be seen in the messaging. This is currently working. 

In the first example here it looks like they are just trying to make the message on initialize. In that case you can just do something like this on setup:
```jsx
message: textContent.quotePage.scriptings.purchasePriceMinimum.replace(":icaContactNumber", textContent.constants.icaContactNumber)
```

I see what @MaximKoshevoy suggested was to pass a "dummy" param to the validator to get it to run messageReplace like `'oppMin:dummyValue'`. That definitely works. But again messageReplace is to allow dynamic values based on params passed into the validator. If there are no params then you should just prebuild the message.
