### ISSUE TITLE
Locale not found! Make sure it is spelled correctly and the locale file is loaded.

### ISSUE THREAD

**Issue by sanjivanid** [dockwa/simple-react-validator#156]

**Comment by stuyam** [comment]
Not sure what this means, can you elaborate?

**Comment by riorinald** [comment]
![image](https://user-images.githubusercontent.com/41993762/68289453-1b9a3300-00c1-11ea-8039-47a32885d7c2.png)
@stuyam here is the screenshot
i'm facing the same issue i guess

**Comment by stuyam** [comment]
Are you trying to use a locale and it's not working? What are you trying? Are you including the locale in the front end or is this just the default with nothing being included? If anyone has some code to show that would be great

**Comment by riorinald** [comment]
no just set by default like this
`this.validator = new SimpleReactValidator({autoForceUpdate: this});`

then solved by add locale parameter and set 'en'
`this.validator = new SimpleReactValidator({autoForceUpdate: this, locale: 'en'});`

**Comment by stuyam** [comment]
This should be fixed in the latest release https://github.com/dockwa/simple-react-validator/releases/tag/1.3.0

**Comment by mohammadrezahayati** [comment]
hi, thank you for your library 
I get this error for Farsi lang.
 simple-react-validator.min.js:474 Locale not found! Make sure it is spelled correctly and the locale file is loaded.

**Comment by mohammad-chavoshipor** [comment]
hi
this my version "simple-react-validator": "^1.6.0",
i get this error for Farsi lang and @types typescript
react_devtools_backend.js:4049 Locale not found! Make sure it is spelled correctly and the locale file is loaded. 
    at CreateTicket (http://localhost:3000/main.55fd68b19a1be7f6ac5e.hot-update.js:39:87)
    at Route (http://localhost:3000/static/js/vendors~main.chunk.js:36721:29)
    at Switch (http://localhost:3000/static/js/vendors~main.chunk.js:36923:29)
    at Router (http://localhost:3000/static/js/vendors~main.chunk.js:36352:30)
    at BrowserRouter (http://localhost:3000/static/js/vendors~main.chunk.js:35875:35)
    at main
    at div
    at App

**Comment by gajjartejas** [comment]
Look like locate is included bu not used any where,

however I did this and worked.

1. Create a new file and copy included required localisations,
2. Import this to your apps entry point
```javascript
import { addSimpleReactValidatorFrench, addSimpleReactValidatorPortuguesse } from 'app/i18n/validators';
addSimpleReactValidatorFrench();
addSimpleReactValidatorPortuguesse();
```

```javascript
import SimpleReactValidator from 'simple-react-validator';

export const addSimpleReactValidatorFrench = () => {
  // French
  SimpleReactValidator.addLocale('fr', {
    accepted: 'Le champ :attribute doit être accepté.',
    after: 'Le champ :attribute doit être après :date.',
    ...
    ...
    ...
    string: 'Le champ :attribute doit être une chaîne.',
    typeof: "Le champ :attribute n'est pas le type correcte de :type.",
    url: 'Le champ :attribute doit être un url.',

  });
};

export const addSimpleReactValidatorPortuguesse = () => {
  // French
  // @ts-ignore
  SimpleReactValidator.addLocale('pt', {
    accepted: ':attribute devem ser aceitos.',
    after: ':attribute deve ser depois de :date.',
    ...
    ...
    ...
    string: ':attribute deve ser um conjunto de caracteres.',
    typeof: ':attribute deve ser do tipo :type.',
    url: ':attribute deve ser uma url.',


  });
};
```

Uses
```javascript
  const selectedLanguage = useSelector((state: IState) => state.loginReducer.selectedLanguage);

  let validator = React.useRef<SimpleReactValidator>(new SimpleReactValidator());

  useEffect(() => {
    validator.current = new SimpleReactValidator({ locale: selectedLanguage });
  }, [selectedLanguage]);

```
