### ISSUE TITLE
TypeError: Cannot read property 'rule' of undefined

### ISSUE THREAD

**Issue by chaudharykiran** [dockwa/simple-react-validator#16]
I am using ReactJs hot reloader and simple-react-validator. But I am getting Cannot read property 'rule' of undefined continuosly.

**Comment by stuyam** [comment]
I am not very familiar with React hot reloader. Is that was is causing the problem? Do you get that error when you are not using hot reloader?

**Comment by stuyam** [comment]
Closing for now unless there is more info or anyone else has this issue
