### ISSUE TITLE
Is this Compatible with IE11?

### ISSUE THREAD

**Issue by ejazhussain** [dockwa/simple-react-validator#168]
I am using this package with React and Typescript application. All other browsers working fine except IE11.
see below image

![2019-12-03_23-33-02](https://user-images.githubusercontent.com/19267065/70098927-5ee6b380-1625-11ea-909b-7f25f2142ac2.png)

**Comment by stuyam** [comment]
Seems like you may be right, I just tried the example in browser stack and it got the same error: 
![image](https://user-images.githubusercontent.com/1553779/70170499-c7bc4300-169a-11ea-86d3-61da3233cca0.png)

Doing some more research it seems to be related to the way Babel is processing the library and is an open issue with them. https://github.com/babel/babel/issues/7597 There are a few options it seems to get around it so will have to do some more research and testing.

**Comment by ejazhussain** [comment]
is there any quick workaround you can suggest while waiting for better fix?

**Comment by Abo-Gabal** [comment]
i have the same problem one i open react in ie11 
while i followed steps  at "7597" but error still exists
'Symbol' is undefined

**Comment by stuyam** [comment]
It doesn't work in IE11 because of babel transpiling.
