### ISSUE TITLE
Validation type email is too strict

### ISSUE THREAD

**Issue by allermand** [dockwa/simple-react-validator#18]
It seems the standard validation for the local part (the stuff before @) of an email is too strict. 
Please see this article on the subject: https://en.wikipedia.org/wiki/Email_address#Local-part

**Comment by allermand** [comment]
Guess the regex should be something like:
/^[A-Z0-9._!#$%&'*+-/=?^_`{|}~]+@[A-Z0-9.-]+\.[A-Z]{2,}$/i

**Comment by stuyam** [comment]
Good point, I will work on that and get back to you soon!

**Comment by stuyam** [comment]
This will be fixed and included in the next major release you can follow along here: https://github.com/dockwa/simple-react-validator/pull/20
