### ISSUE TITLE
Turkish Language Locale file should be added

### ISSUE THREAD

**Issue by oguzhanozpinar** [dockwa/simple-react-validator#181]
To use this library on a local project, I want to add Turkish languıage file

**Comment by oguzhanozpinar** [comment]
While following the process you mentioned in CONTRIBUTING.md, when I run the command npm install , it producess an error :
![image](https://user-images.githubusercontent.com/49562515/71903638-94774300-3175-11ea-8455-c1ca6be0ac7a.png)

**Comment by stuyam** [comment]
Here is a helpful link to help Turkish translations: https://github.com/caouecs/Laravel-lang/blob/master/src/tr/validation.php

As for the error you are seeing, looks like something lower level. I would suggest you are running a newer version of npm. Im running npm `6.13.0` and it works for me right out of the box on mac.

**Comment by oguzhanozpinar** [comment]
I suspect that error is caused by my node version, may I learn yours ? As I researched, node 12 and gulp 3 wont work together

**Comment by stuyam** [comment]
```
> node -v
v10.16.0
> npm -v
6.13.0
```

**Comment by stuyam** [comment]
I think I had to downgrade for a different project recently and haven't upgraded again. I should be testing on the latest I thought I was.

**Comment by stuyam** [comment]
I upgraded to:
```
> node -v
v13.5.0
> npm -v
6.13.4
```
and now I am getting the same error as you.

**Comment by oguzhanozpinar** [comment]
https://stackoverflow.com/questions/55921442/how-to-fix-referenceerror-primordials-is-not-defined-in-node

**Comment by stuyam** [comment]
Well this seems like another issue, but for now you can just add the Turkish file without building to open a PR and Ill make a new issue regarding the node gulp issue.

**Comment by oguzhanozpinar** [comment]
I am currently testing it on my project. As soon as I implement it, i will open a PR.

**Comment by oguzhanozpinar** [comment]
No matter how I try i could not make it work. I also tried the existing language supports but they are also seem not to work. I couldnt find any existing issues related to localization.

**Comment by stuyam** [comment]
@oguzhanozpinar I just upgraded to gulp 4 and it seems to be working locally now. I also tested the French locale locally and that seemed to work too. Give it another try and keep me posted, I can help you if you run into trouble, but you should just be able to make the new locale in `src/locale/` and that would be all, then I can build for release.

**Comment by stuyam** [comment]
#
