### ISSUE TITLE
When click on button submit first then on change event not remove Required error message?

### ISSUE THREAD

**Issue by Inam337** [dockwa/simple-react-validator#189]
index.js:1375 Warning: Failed prop type: You provided a `value` prop to a form field without an `onChange` handler. This will render a read-only field. If the field should be mutable use `defaultValue`. Otherwise, set either `onChange` or `readOnly`.
![test](https://user-images.githubusercontent.com/18351912/72256305-ad2aa180-362a-11ea-9cd2-b5f5954b00a9.png)

**Comment by stuyam** [comment]
This is a React specific error. Also SRV won't work with a read-only field because it checks React state which is not being set. Do you have more specific examples of what you are trying to accomplish?
