### ISSUE TITLE
Numeric should return true for negative numbers

### ISSUE THREAD

**Issue by LeonSkrilec** [dockwa/simple-react-validator#190]
Rule "numeric" is described as "Must be a number of any type." 
I think that includes negative numbers. 

Currently, regex for checking numeric type only validates positive numbers.

`numeric(val) {
      return this.testRegex(val,/^(\d+.?\d*)?$/);
    }
`

**Comment by stuyam** [comment]
Yeah that seems to make sense, should we have a validator for only positives too? Or I guess you could use a `min:0,num` so require positive numbers. I know for example we use `numeric` for dollar input values which we require to be positive.

**Comment by LeonSkrilec** [comment]
Yeah I guess this would work: 
Positive numbers: "numeric|min:0,num"
All numbers: "numeric"
Negative numbers "numeric|max:0,num"

**Comment by stuyam** [comment]
Yeah I like that, I will add the info to the documentation as well, working on the change now.

**Comment by stuyam** [comment]
@LeonSkrilec it looks like in your profile you are from Slovenia. If you know Slovenian feel free to open a pull request to add a Slovenian translation file to SRV.

**Comment by LeonSkrilec** [comment]
I will, I think I have already written these messages for some Laravel
project a while ago.

**Comment by stuyam** [comment]
Closed in latest release.
