### ISSUE TITLE
"accepted" returning empty object?

### ISSUE THREAD

**Issue by charlie-barrows** [dockwa/simple-react-validator#197]
I ran into a problem with 1.4.3 not validating in my application and wondered if the recent change to the "accepted" rule was intentional?

from:
`rule: val => val === true`
to:
`rule: val => {}`

Thanks!

**Comment by stuyam** [comment]
You are right! I mean to change the `required` validator and change the `accepted` one! Working on a fix now!

**Comment by stuyam** [comment]
Thanks for finding this, fixed in the latest release 1.4.4
