### ISSUE TITLE
Working with RegEx(This is a question!)

### ISSUE THREAD

**Issue by ardavanmofidi** [dockwa/simple-react-validator#202]
Hey guys,
Thanks for the cool library...

How can I use a validation with regex? Could you please give us an example?

Cheers,

**Comment by ardavanmofidi** [comment]
And this is a specific use case I am trying to use:

<div className="form-group">
        <label>Title</label>
        <input className="form-control" value={this.state.title} onChange={this.setTitle} />
        {this.validator.message('title', this.state.title, 'required|regex:/^[0-9]{10}+$/')}
</div>

**Comment by jrsarath** [comment]
Hey Bud try this
`
<div className="form-group">
        <label>Title</label>
        <input className="form-control" value={this.state.title} onChange={this.setTitle} />
        {this.validator.message('title', this.state.title, ['required',{regex: '/^[0-9]{10}+$/'}])}
</div>
`

**Comment by stuyam** [comment]
Yeah give what @jrsarath suggested at try, breaking it out into the array syntax. However what you are doing _should_ also be working. Could you give a little more explanation of what is going on. What is happening when you try it?

**Comment by jrsarath** [comment]
> Yeah give what @jrsarath suggested at try, breaking it out into the array syntax. However what you are doing _should_ also be working. Could you give a little more explanation of what is going on. What is happening when you try it?

He got special characters in the RegEx pattern, Docs suggests putting them in array format if there's special characters in RegEx pattern, and tbh in 2020 RegEx without special characters are almost instinct

**Comment by ardavanmofidi** [comment]
I tried what @jrsarath suggested and it didn't work:
Code:
`{this.validator.message('title', this.state. title, ['required',{regex: '/^[0-9]{10}+$/'}])}`

SyntaxError: 
Invalid regular expression: //^[0-9]{10}+$//: Nothing to repeat

I also tried putting them in array and it was valid all the time except when it was null.  So, it worked but it didn't work correctly. the question is, is this a right way to pass the arrays?
`{this.validator.message('title', this.state.title, ['required',{regex: ['^','[','0','-','9',']','{','1','0','}','+','$']}])}`

**Comment by ardavanmofidi** [comment]
Any updates guys?

**Comment by jrsarath** [comment]
hey man, sorry been busy post the actual regex pattern will you ?
