### ISSUE TITLE
Negative integers failed the integer test.

### ISSUE THREAD

**Issue by henry132109** [dockwa/simple-react-validator#215]
[It happens on your example page too](https://dockwa.github.io/simple-react-validator/)
e.g. -1, -2, -1234
This fix should be quick.

**Comment by stuyam** [comment]
Good find. Yeah we should make sure all number validators have the ability to go negative.

**Comment by stuyam** [comment]
Released in latest: https://github.com/dockwa/simple-react-validator/releases/tag/1.6.0
