### ISSUE TITLE
Custom message show in Input Field

### ISSUE THREAD

**Issue by softwaresolution357** [dockwa/simple-react-validator#221]
this.validator = new SimpleReactValidator({
      messages: {
        email: "Invalid mail Id"},
    });
This is input field
 <input
                        type="text"
                        className="form-control"
                        id="email"
                        placeholder="Email"
                        required=""
                        name="email"
                        value={email}
                        onChange={this.handelChange}
                      />
                      {this.validator.message('email', email, 'required|email')}
I want to show my custom message in my input field, But It isn't reflect input field.

**Comment by softwaresolution357** [comment]
Input field validation message show

**Comment by azientar** [comment]
I'm also experiencing the issue where custom messages won't display.

**Comment by stuyam** [comment]
In this case you are using `'required|email'` which means `required` will show the validation message first so if nothing is entered the required message shows. Once _required_ passes then it will test against the _email_ validator and should show your custom messaging there. If you want to set a custom message on that field for all validators you can use the _default_ message option to set it it as the default message for that validator:
```jsx
{this.validator.message('email', email, 'required|email', {messages: {default: "Invalid mail Id"}})}
```
