### ISSUE TITLE
custom validator not working when put inside a loop

### ISSUE THREAD

**Issue by anugaur2210** [dockwa/simple-react-validator#222]
I have an array with four values. When I am looping over this array, it works for other values when I provide the last value of that array and doesn't work at all if I don't provide value for the last field.
 I have an array [ 012, 890a, %67, ' '] - it does not work for this scenario.

 I m checking for alpha numeric value using my own custom validator.

PFB sample code:
```jsx
{exampleList.map((item: any, index: number) => {
  return (
    <div>
      <div>
        <input
          type="text"
          name="example"
          onChange={(event) => this.handleChange(event)}
          value={item}
        />
        {this.validator.message("example", item, 'alphaNumCheck', { className: 'error' })}
      </div>
    </div>
  )}
)}
```
Below is my custom validator
```jsx
alphaNumCheck: {
  message: 'Incorrect entry',
  rule: (val: string, params: any, validator: any) => {
    return validator.helpers.testRegex(val, /^[A-Za-z0-9]+$/)
  }
}
```
Could you please check.

**Comment by anugaur2210** [comment]
Also, if I use inbuilt validator - alpha_num inside a loop, it is still not working.Please help here

**Comment by stuyam** [comment]
The name of the key field you are validating as the first param of the `message` method needs to be unique. So if you are looping over it with a `for` loop for example you could do something like:

```jsx
{this.validator.message(`example-${index}`, item, 'alphaNumCheck', { className: 'error' })}
```

You just need to find a way to make it unique for each because that it how it identifies that particular validator.

**Comment by anugaur2210** [comment]
Thanks for the response. Its working now with unique value. You can close this issue.
