### ISSUE TITLE
Dynamic validation [feature]

### ISSUE THREAD

**Issue by gtaylor44** [dockwa/simple-react-validator#23]
At the moment, there doesn't seem a nice way to do dynamic validation. It's much more convenient to call "allvalid()" instead of performing validation one by one. 

I have a scenario where user has a drop down. Validation for the drop down field should only be applied if the drop down value is equal to a specific value, otherwise this field should not be validated. 

Could you please let me know an elegant way to handle this with your library?

This is my proposed solution (new parameter 'disabled'):

![image](https://user-images.githubusercontent.com/11572604/48549450-f34f7c80-e923-11e8-851d-8657bd5e2862.png)

**Comment by stuyam** [comment]
Support for this is coming in v1.0.0 which is probably getting release today. See the documentation here: https://github.com/dockwa/simple-react-validator#conditional-fields

`purgeFields` allows you to reset what things are to be validated on each render and you only include the fields you want to be validated if that makes sense?

**Comment by stuyam** [comment]
1.0.0 released just now: https://github.com/dockwa/simple-react-validator/releases/tag/1.0.0
