### ISSUE TITLE
Hi, Two questions

### ISSUE THREAD

**Issue by ZhaopingLuo** [dockwa/simple-react-validator#24]
1. How do I clear error messages after I submit? After I submit, I tried to clear all the fields, but suddenly all required error messages show up.
2. How do I set an optional field? In my case, check the phone number if the user fills it, but it's not required.

**Comment by ZhaopingLuo** [comment]
I just figured out the first question.
this.validator.hideMessages();

**Comment by stuyam** [comment]
Make sure you are up to date on v1.0.0 of the library, in the latest release it makes optional fields truly optional. As long as your don't use the `required` validation it will be considered optional.

**Comment by ZhaopingLuo** [comment]
> Make sure you are up to date on v1.0.0 of the library, in the latest release it makes optional fields truly optional. As long as your don't use the `required` validation it will be considered optional.

Thank you.
