### ISSUE TITLE
Regex for time

### ISSUE THREAD

**Issue by tiberiu1995** [dockwa/simple-react-validator#254]
Hello, I currently have this regex for validating time: 
`regex:^(([0-1]?[0-9])|2[0-3]):[0-5][0-9]$`
Since I use '|' operator, I used the regex in an array, as it was written in docs:
`['regex:^(([0-1]?[0-9])|2[0-3]):[0-5][0-9]$']`
But, nevertheless, because of the ':' character that splits hours from minutes, it doesn't parse the part after ':'. Can you help me solve the problem?``

**Comment by stuyam** [comment]
The syntax should be more like this, a JS object in an array: 
`[{regex: '^(([0-1]?[0-9])|2[0-3]):[0-5][0-9]$'}]`

**Comment by tiberiu1995** [comment]
Thank you, it worked! Never thought to do it this way.

**Comment by stuyam** [comment]
@tiberiu1995 I could definitely improve the documentation for regex in regards to this. Thank you 👍
