### ISSUE TITLE
How can we validate the Password field

### ISSUE THREAD

**Issue by Tarkik3798** [dockwa/simple-react-validator#261]
The password must be contain Minimum eight characters, at least one uppercase letter, one lowercase letter, one number and one special character:

I tried using Regex but it won't work.

Here is my form input field code:
------------------------------------
<label className="col-12 edit-address-input-label">
								{localStorage.getItem("loginLoginPasswordLabel")}{" "}
								{this.validator.message("password", this.state.password, "required",{
									regex:"^(?=.*[a-z])(?=.*[A-Z])(?=.*\d)(?=.*[@$!%*?&])[A-Za-z\d@$!%*?&]{8,}$"
								})}
							</label>
							<div className="col-md-9">
								<input
									type="password"
									name="password"
									onChange={this.handleInputChange}
									className="form-control edit-address-input"
								/>
							</div>
--------------------------------------------
here is my validator defination:
	this.validator = new SimpleReactValidator({
			autoForceUpdate: this,
			messages: {
				required: localStorage.getItem("fieldValidationMsg"),
				string: localStorage.getItem("nameValidationMsg"),
				email: localStorage.getItem("emailValidationMsg"),
				regex: localStorage.getItem("passwordValidationMsg"),
				min: localStorage.getItem("minimumLengthValidationMessage"),
			},
		});

**Comment by stuyam** [comment]
The syntax should be an array with "required" something like this:
```jsx
this.validator.message("password", this.state.password, ["required", {regex:"^(?=.*[a-z])(?=.*[A-Z])(?=.*\d)(?=.*[@$!%*?&])[A-Za-z\d@$!%*?&]{8,}$"}])
```

You could also do your min via a validator to give more specific validation messaging like:
```jsx
this.validator.message("password", this.state.password, ["required", {min: 8}, {regex:"^(?=.*[a-z])(?=.*[A-Z])(?=.*\d)(?=.*[@$!%*?&])[A-Za-z\d@$!%*?&]{8,}$"}])
```
