### ISSUE TITLE
How to conditionally validate fields

### ISSUE THREAD

**Issue by atreya-yelishetti** [dockwa/simple-react-validator#263]
![image](https://user-images.githubusercontent.com/49288643/91778807-48bc5280-ebb9-11ea-9b51-3788c9610791.png)
From the above image, I would like to validate input field and a dropdown only when the checkbox is selected.

And also how to validate dropdown ?

**Comment by stuyam** [comment]
I would suggest only adding the validation rules being rendered if the checkbox is checked. It will only validate what is being set by the `message` method so you can do anything with that method. And use the [purgeFields](https://github.com/dockwa/simple-react-validator#3-conditional-fields) method on rerender so if it gets checked and unchecked it will enable or disable the conditional fields.

Example
```jsx
{isCheckboxChecked ? this.validator.message(............) : null}
```
