### ISSUE TITLE
onBlur doesn't work properly

### ISSUE THREAD

**Issue by shuweili1122** [dockwa/simple-react-validator#289]
Is it just me or it's for everyone that the onBlur doesn't work so properly, say I have two input boxes with onBlur error check, when I tab into the first inputbox, and enter something that doesn't meet the onBlur check for this first box, and then tab out to the second box; the onBlur check for the first box doesn't get triggered until after I enter some value into the second box...

Simply put, onBlur for error check doesn't work when the focus is lost

I tried this on both React 15.0.1 and 16.8.0

**Comment by stuyam** [comment]
Sounds like you need to enable the `autoForceUpdate` to trigger the rerender: https://github.com/dockwa/simple-react-validator#note-autoforceupdate

**Comment by shuweili1122** [comment]
@

> Sounds like you need to enable the `autoForceUpdate` to trigger the rerender: https://github.com/dockwa/simple-react-validator#note-autoforceupdate

Thx, man!!!
I was trying to this.forceUpdate() in componentDidUpdate upon change of my props...
