### ISSUE TITLE
message always disply

### ISSUE THREAD

**Issue by deoracle** [dockwa/simple-react-validator#291]
` const formValidator = useRef(new Validator());`

`<input name="name" onChange={testOnChangeHadler} value={value}  onBlur={formValidator.current.showMessageFor('name')} />
 {formValidator.current.message('name', value, 'required')}
`

`const isFormValid = formValidator.current.allValid();
  if(!isFormValid) {
            formValidator.current.showMessages();
        } else {
            console.log('done')
        }`

but message always display near input field

**Comment by KaranKhirsariya** [comment]
Change onBlur attribute value to
```
onBlur={()=>formValidator.current.showMessageFor('name')}
```
Attribute value shouldn't be a function call. There was a typo in ReadMe example so it's [fixed](https://github.com/dockwa/simple-react-validator/pull/315) now.
