### ISSUE TITLE
Validation Problem for Dynamic Elements

### ISSUE THREAD

**Issue by kerembeyazit** [dockwa/simple-react-validator#322]
I have an array and mapping form elements based this array. If some element removed from array, validator cannot detect the removed element and showing validation error for this.

How can I check the validation for removed elements from HTML?

**Comment by stuyam** [comment]
Sounds like you want to use the validator `purgeFields()` method. Should just be able to put it in the top of your render method to clear the validation on rerender. It's not required to most setups but when you have fields that change it is. Here is more documentation on how it works: https://github.com/dockwa/simple-react-validator#3-conditional-fields

**Comment by kerembeyazit** [comment]
Thanks. Problem solved.
