### ISSUE TITLE
Decimal Integer fails integer test

### ISSUE THREAD

**Issue by fandiario** [dockwa/simple-react-validator#365]
While using "required|integer", my value number of "5.10" fails integer test and read as failure. But it supposed to be true...Please Help. Thamk you before.

**Comment by stuyam** [comment]
If you want "5.10" to be valid you should use the `numeric` rule: https://github.com/dockwa/simple-react-validator#numeric the `integer` rule is only for integers aka whole numbers 1, 2, 3, 100, -54 and not decimals.

**Comment by fandiario** [comment]
@stuyam Thank you very much. It's working now.
