### ISSUE TITLE
How to pass regex with '|' or ',' for example ^([a-zA-Z]|[a-zA-Z][a-zA-Z0-9]{0,61})$

### ISSUE THREAD

**Issue by ajainsws** [dockwa/simple-react-validator#388]
Hi,

As per the document 
---------------------
regex:pattern
Must match a regex.
Options: regex it must match.
**Note: if your regex uses a | or , or other special characters use the array syntax to define the rule.**

can anyone explain how can we add array syntax for such kind of regex pattern  ^([a-zA-Z]|[a-zA-Z][a-zA-Z0-9]{0,61})$

**Comment by ajainsws** [comment]
I tried as

required : true | [{regex: '^([a-zA-Z]|[a-zA-Z][a-zA-Z0-9]{0,61})$'}]

but also not working.

**Comment by stuyam** [comment]
Try this: `['required', {regex: /^([a-zA-Z]|[a-zA-Z][a-zA-Z0-9]{0,61})$/}]`

**Comment by haresh6x** [comment]
If I use the regex pattern, how do i modify the message? Currently it only shows message like "the field-name must match the required pattern". I want to give the message such as "the field-name must start with T followed by numbers"

**Comment by stuyam** [comment]
See https://github.com/dockwa/simple-react-validator/issues/391
