### ISSUE TITLE
How do i run validation on blur

### ISSUE THREAD

**Issue by mnksingh** [dockwa/simple-react-validator#42]
Right now i can only trigger validation on start or on submit with this.validator.showMessages() but my form is really long and i want to trigger it on blur, please explain how can i do it or extend the current library.

**Comment by stuyam** [comment]
A few people have asked for this, Im not sure if there is way currently that this is possible.

I think we could add a validator method that could be called with the key you want to show individual messages. The idea being you could put that in an `onBlur` react handler and show an individual validation message one at a time.

I really like this idea and we should go forward on developing this feature 👍

**Comment by neilmaledev** [comment]
Up. I'm looking forward for it too.

**Comment by Jebble** [comment]
Up!

The only thing I'm missing is real time validation before submission to instantly let people know a field was required or doesn't match without having to submit and seeing all the errors at once.

**Comment by millturnK** [comment]
Ditto! Love your work, you've saved me so much time. Excellent coding :-).

**Comment by stuyam** [comment]
Featured added in #92 and coming to v1.1.0

**Comment by stuyam** [comment]
Out in latest release: [1.1.0](https://github.com/dockwa/simple-react-validator/releases/tag/1.1.0)
