### ISSUE TITLE
how to create custom validation for 1 field  ?

### ISSUE THREAD

**Issue by ashishitechnotion** [dockwa/simple-react-validator#5]
how to create custom validation for 1 field 

this library check all field validation

**Comment by stuyam** [comment]
hmmm, that's interesting and not a use case I have thought of. That is a reasonable enough request let me make that happen real quick.

**Comment by stuyam** [comment]
Added a `fieldValid('field_name')` method to check if a single field is valid or not in v.0.0.5: https://github.com/dockwa/simple-react-validator/releases/tag/v0.0.5
