### ISSUE TITLE
How can set a custom message for a field?

### ISSUE THREAD

**Issue by JELugoM** [dockwa/simple-react-validator#55]
Im already use your example code to set my message on spanish:
this.validator = new SimpleReactValidator({
  messages: {
    email: 'That is not an email.'
    // OR
    default: 'Validation has failed!'  // will override all messages
  },
}

but Im still getting the message on english, , here's my code:

```
constructor(props) {
    super(props);
    this.state = {
      name: '',
    };

   this.validator = new Validator({
      element: message => (
        <span style={error}>
          <i className="fa fa-exclamation-circle" aria-hidden="true" />
          { ` ${message}`}
        </span>
      ),
      messages: {
        name: 'El campo nombre es requerido',
      },
    });

<div className="form-group">
 <label htmlFor="name">Nombre: *</label>
 <input
 type="text"
 name="name"
 onChange={this.onChangeHandle}
 className="form-control"
 id="name"
 placeholder="Nombre Campaña / Cupón"
 />
 {this.validator.message('name', this.state.name, 'required|alpha')}
 </div>
```

**Comment by stuyam** [comment]
I see the problem, the key for the message should be the validator rule name you want it to show on not the attribute of field (aka 'alpha' not 'name). For example it should look like this:
```javascript
messages: {
  alpha: 'El campo nombre es requerido',
},
```

and you could do this to make it dynamic:
```javascript
messages: {
  alpha: 'El campo :attribute es requerido',
},
.....
{this.validator.message('nombre', this.state.name, 'required|alpha')}
```

Let me know if you have any questions! Enjoy 👍

**Comment by stuyam** [comment]
It would be really cool to localize this project! Haven't thought of how it would work before but that would be awesome!

**Comment by JELugoM** [comment]
Awesome, it works, thanks!!!

**Comment by kerembeyazit** [comment]
This isn't working anymore. 

```
messages:{
	selectFile: 'Please select a file.'
}

```
`{this.validator.message('document_name', this.state.document_name, 'required|selectFile')}`

**Comment by BSThisarasinghe** [comment]
Does anyone know how to set two messages for same field in different scenarios.

    `messages:` {
                email: 'That is not an email.'
            },
        });`

Here I want to change the required message as well.

**Comment by stuyam** [comment]
@BSThisarasinghe you can do it in the initializer options for the whole component or inline like this:
```jsx
this.validator = new SimpleReactValidator({
  messages: {
    required: 'This field is required',
    email: 'Some message'
  }
});

// OR

{this.validator.message('email', this.state.name, 'required|email'), {messages: {required: 'This field is required', email: 'Some message'}} }
```

**Comment by BSThisarasinghe** [comment]
Oh now it's clear. Thank you sso much.
