### ISSUE TITLE
Validation Problem

### ISSUE THREAD

**Issue by ashishitechnotion** [dockwa/simple-react-validator#6]
validation proper not working on the same page.

like login button for login tab and signup button for signup tab.
login tab validation fired on signup button and signup tab validation fired on login button.

Email validation issues
m..k.@yahoo.com
m..k.@yahoo...com
m.k@-yahoo.com

**Comment by stuyam** [comment]
@ashishitechnotion can you give me more information or a code snippet that you are using, Im not following

**Comment by ashishitechnotion** [comment]
Hello Stuart


i'm use below code for validation

  if(that.validator.fieldValid("state_id") && 
that.validator.fieldValid("city_name"))
       {

     }
     else
     {
         that.validator.showMessages();
         that.forceUpdate();
     }

**Comment by stuyam** [comment]
@ashishitechnotion are you using one of these lines to set the values of the validator?
```
{this.validator.message('email', this.state.email, 'required|email', 'text-danger')}
```
You need to use that to link up the value with what you are trying to validate. It might be useful to make a codepen or jsfiddle as an example and would make it easier for me to help you.

**Comment by ashishitechnotion** [comment]
@stuyam  , i have attached demo code file, for validation error.
[myapp.zip](https://github.com/dockwa/simple-react-validator/files/1882706/myapp.zip)

**Comment by ashishitechnotion** [comment]
@stuyam  any update ??

**Comment by stuyam** [comment]
@ashishitechnotion I got a chance to look at it. You should be using __one__ validator per form. You are using the same validator for both forms. You should be creating two validators and using one for each form. That should fix your problem.

**Comment by ashishitechnotion** [comment]
@stuyam , OK thanks.
