### ISSUE TITLE
How to use

### ISSUE THREAD

**Issue by ShoutongLiu** [dockwa/simple-react-validator#61]
this.validator = new SimpleReactValidator()
 but tip  SimpleReactValidator is not defined

**Comment by stuyam** [comment]
@ShoutongLiu can you give me more information oh your setup? Are you loading Simple React Validator before this files is getting loaded? Can you share how you are using it?

1) Check in your browser console that SimpleReactValidator is loaded
2) If you are using something like browserify or webpack to load your packages make sure you are importing the package

**Comment by ShoutongLiu** [comment]
Hi,stuyam,Here are my steps.
1.Introducing SimpleReactValidator into TSX file
2. this.validator = new SimpleReactValidator() in the constructor
3.Finally, I used this. validator. message in input, but it didn't work.
and I print this. validator. message in the console.
I saw in the console that this. validator. message is an empty object
Is that right?
code:
import SimpleReactValidator from 'simple-react-validator'
class Login extends React.Component<any, any> {
    validator: any
    constructor(props: any) {
        super(props)
        this.validator = new SimpleReactValidator()
        this.state = {
            email: '',
        }
    }

**Comment by stuyam** [comment]
Yeah `this.validator.message` will probably show as nothing in the console. You need to set a rule and also call `this.validator.showMessages();` to actually show the error messaging. Id add a message like `{this.validator.message('email', this.state.email, 'required|email'}`. Make sure to follow these 3 steps: https://github.com/dockwa/simple-react-validator#3-easy-steps

**Comment by ShoutongLiu** [comment]
Got it.Thank you so much！
