### ISSUE TITLE
Input file 

### ISSUE THREAD

**Issue by SteiNNx** [dockwa/simple-react-validator#63]
How can I implement a validation with an input file?
I put it in required but when I attach a file I still get the required message ..

**Comment by SteiNNx** [comment]
![2](https://user-images.githubusercontent.com/30225200/54046748-04164d80-41b4-11e9-8744-f14d287288c0.PNG)
![1](https://user-images.githubusercontent.com/30225200/54046749-04164d80-41b4-11e9-9759-b40501590575.PNG)

**Comment by stuyam** [comment]
I would add an `onChange` event to a file being added and then set some state like `fileAdded` as a boolean and then use the `accepted` [validation rule](https://github.com/dockwa/simple-react-validator#accepted) to ensure that it is set to true and set a custom message.

**Comment by SteiNNx** [comment]
is already corrected, thanks
