### ISSUE TITLE
validator resetField

### ISSUE THREAD

**Issue by SanaAmir** [dockwa/simple-react-validator#65]

**Comment by SanaAmir** [comment]
Hello,

How do I reset errors in my form? I have a modal window and when reopen,  the previous error message showing.

**Comment by Arrow66** [comment]
hey stuyam 
I am also facing this problem ; when i reset forms after submission validation get triggered and the error messages are showing . any fix for this .

**Comment by SanaAmir** [comment]
Hi,
Use this  this.validator.hideMessages()
*Thanks and Regards,*

*Ameerjohn T*

**Comment by stuyam** [comment]
Task: document hideMessages method on readme

**Comment by stuyam** [comment]
Documented in latest release. https://github.com/dockwa/simple-react-validator/releases/tag/1.0.6
