### ISSUE TITLE
Validations are slow when using more than one custom validations 

### ISSUE THREAD

**Issue by Arrow66** [dockwa/simple-react-validator#76]
` this.validator = new SimpleReactValidator({
      messages:{
          isDate:"Invalid Date Format"
      },
      validators: {
        isDate: { 
          rule: function(val, params, validator) { 
            console.log("Validator:",val);
            return validator.helpers.testRegex(moment.isMoment(val) ? val.format("YYYY-MM-DD HH:mm:ss"):val ,/(?:(\d{4})([\-\/.])([0-3]?\d)\2([0-3]?\d)|([0-3]?\d)([\-\/.])([0-3]?\d)\6(\d{4}))(?:\s+([012]?\d)([:hap])([0-5]\d))?/i);
          } 
        }
      }
    });`

is This because of regex ? . Or is there any Fix for this issue ?. I've been facing this weird issue when i was started using more than one **isDate**   validation on a Date picker .

**Comment by Arrow66** [comment]
Sorry My bad .
Fixed with using    this.forceUpdate();
Kudos to the Developer :1st_place_medal:

**Comment by stuyam** [comment]
Glad you got it fixed 👍
