### ISSUE TITLE
Can not validate DatetimePickerTrigger using MomentJS

### ISSUE THREAD

**Issue by nhatquan160697** [dockwa/simple-react-validator#77]
Hi, I have a problem to ask you:

I'm trying to validate Datetime picker using MomentJS but I don't know how does it work. 

This is my code:
`                    <DatetimePickerTrigger
                        moment={this.state.moment}
                        onChange={this.handleChange}>
                        <input type="text" className="style-field-date" value={this.state.moment.format('YYYY-MM-DD HH:mm')} readOnly />
                    </DatetimePickerTrigger>   `

I tried `                    { this.validator.message('date', this.state.moment && moment(this.state.moment, 'DD-MM-YYYY'), 'after:date') }      ` but it didn't work.
Please help me validate this field. 
Thanks you

**Comment by stuyam** [comment]
Does it seem to be related to this issue #66 ? Do you get the message "Date validators require using momentjs https://momentjs.com and moment objects." in your console when you try to run it?
