### ISSUE TITLE
Is there a way to programmatically push validation messages.

### ISSUE THREAD

**Issue by menaka123** [dockwa/simple-react-validator#89]
I am trying to push server side validation messages to the fields.

For example is there a method that can be used to do this =>

```
errors.forEach(item => {
 this.validator.**push**(item.fieldname, item.message)
})

this.validator.showMessages()
this.forceUpdate()
```

I used push method as an example here.

**Comment by stuyam** [comment]
For server side validation I suggest using the `messageWhenPresent` method: https://github.com/dockwa/simple-react-validator#available-public-methods

It prints the message when there is a message set. Usually just put it at the end of the form, so when something like a certain state key is set to the message it will show the validation message. To get it to work sort of how you are intending you could have a `messageWhenPresent` after each `message` for each type of message that is could respond with.

May be a possible future feature request. Hope it helps.
