### ISSUE TITLE
E-Mails with a "-" do not validate

### ISSUE THREAD

**Issue by jfoty40** [dockwa/simple-react-validator#96]
E-Mail validation fails if the emails contains a "-". In the real world this should not make a user fail the email validation

**Comment by stuyam** [comment]
Are you sure about that? Are you on the most up to date version? Here is a test I did in regex101: https://regex101.com/r/mdkAhj/2 it seems to pass with dashes in it. Do you have more details on what is happening?

**Comment by stuyam** [comment]
Closing because when using https://dockwa.github.io/simple-react-validator I was able to use `-` in both parts of the email.

**Comment by jfoty40** [comment]
Sorry about that. I agree it is working on your test site. Did you guys recently release an update? In production I had a user that could not login with the email "moni_casarez@yahoo.com". The only validation I was using was the simple-react-validation with the email validator. Maybe it is not a problem with the package. I will have to test later. I completely removed the validation from the client side after encountering this issue, as it was stopping users from logging in. Thank you guys for looking into this

**Comment by jfoty40** [comment]
I tested this again and after running "npm install simple-react-validator" the error stopped occurring. Thank you I think this bug existed in a previous version. I apologize and will make sure to always update to the most recent version of a package before reporting an issue. Thank you guys again for this package! It saves me a great deal of time when writing validation
